Repository Team-8px/playGround, pull requests merged in 2021-12, with the labels that each got.

#1 Add: 색상추가
  style.css
Labels: documentation

#3 Add: 제목 스타일 추가
  style.css
Labels: good first issue

#4 :memo: Update index
  index.html
  style.css
Labels: 레이아웃

#5 refactor: 스타일변경
  style.css
Labels: 리팩토링

#6 refactor: 스타일 수정
  style.css
Labels: 테스트, 도움 요청, 질문

#7 Hg/layout
  README.md
  index.html
  style.css
Labels: 레이아웃

#8 test: Conflict Maker
  index.html
  style.css
Labels: 테스트, 도움 요청

#14 test: 테스트 커밋입니다.
  index.html
Labels: 테스트

#15 test: 테스트 커밋입니다.
  index.html
Labels: 테스트, 도움 요청, 질문

#16 test: 미진님 해결해주세요!
  index.html
Labels: good first issue

#17 “mj/lay2”
  index.html
Labels: 테스트, 도움 요청, 질문

#21 test: test Commit
  index.html
Labels: good first issue

#22 test: 테스트 커밋입니다.
  index.html
Labels: 도움 요청, 질문

#25 test: test commit
  index.html
Labels: 도움 요청

#27 test : test commit
  index.html
Labels: 도움 요청

#29 test : test commit
  index.html
Labels: 테스트

#30 add : layout 작성
  index.html
  style.css
Labels: 레이아웃

#31 Jy/feat button
  index.html
  script.js
  style.css
Labels: 리팩토링, 기능추가

#32 Jy/fix
  script.js
Labels: 리팩토링

#34 add: 버튼 추가
  index.html
Labels: 레이아웃

#35 test: 버튼 스타일 추가
  index.html
  style.css
Labels: 레이아웃, 테스트
